const PATTERN_EXCLUDE_SPACES = /[\s]/g; // generated by IA
const PATTERN_WORDS = /\p{L}+/gu; // generated by IA
const PATTERN_SENTENCE = /[^.]+\./g; // generated by IA

// exclude spaces characters 
function excludeSpaces(text) {
    return text.replace(PATTERN_EXCLUDE_SPACES, "");
}

// count the characters by type of the text. Exclude spaces or original 
export function countCharacters(text, typeText) {
    const value = typeText === "noSpaces" ? excludeSpaces(text).length : text.length;
    return value;
}

// count the words and senteces 
export function countWordsSenteces(text) {
    const totalCharacters = countCharacters(text, "original");
    const totalWords = totalCharacters > 0 ? text.match(PATTERN_WORDS).length : 0;
    const totalSentences = totalCharacters > 0 && text.match(PATTERN_SENTENCE) ? text.match(PATTERN_SENTENCE).length : 0;
    return { totalWords, totalSentences }
}

// calculate the time to reading
export function calcReadingTime(words) {
    const WORD_PER_MINUTE = 200;
    return words / WORD_PER_MINUTE;
}
