const PATTERN_EXCLUDE_SPACES = /[\s]/g; // generated by IA
const PATTERN_WORDS = /\p{L}+/gu; // generated by IA
const PATTERN_SENTENCE = /[^.]+\./g; // generated by IA
const PATTERN_LIMIT_INPUT = /[^0-9]/g; // generated by IA

// exclude spaces characters 
export function excludeSpaces(text) {
    return text.replace(PATTERN_EXCLUDE_SPACES, "");
}

// count the characters by type of the text. Exclude spaces or original 
export function countCharacters(text, typeText) {
    const value = typeText === "noSpaces" ? excludeSpaces(text).length : text.length;
    return value;
}

// count the words and senteces 
export function countWordsSenteces(text) {
    const totalCharacters = countCharacters(text, "original");
    const wordsMatch = text.match(PATTERN_WORDS);
    const totalWords = wordsMatch ? wordsMatch.length : 0;
    const totalSentences = totalCharacters > 0 && text.match(PATTERN_SENTENCE) ? text.match(PATTERN_SENTENCE).length : 0;
    return { totalWords, totalSentences }
}

// calculate the time to reading
export function calcReadingTime(words) {
    const WORD_PER_MINUTE = 200;
    return words / WORD_PER_MINUTE;
}

// Sanitize input when the user types letter and symbols
export function sanitizeLimitInput(value) {
    return value.replace(PATTERN_LIMIT_INPUT, "");
}

// check the limit of characters 
export function checkLimitCharacters(numCharacters, valueLimit) {
    let limitDefined = valueLimit > 0 ? valueLimit : undefined;
    if (!limitDefined || numCharacters < limitDefined) {
        return { isExceed: false, value: limitDefined };
    } else {
        return { isExceed: true, value: limitDefined };
    }
}

