const PATTERN_LIMIT_INPUT = /[^0-9]/g; // generated by IA

// Sanitize input when the user types letter and symbols
export function sanitizeLimitInput(value) {
    return value.replace(PATTERN_LIMIT_INPUT, "");
}

// check the limit of characters 
export function checkLimitCharacters(numCharacters, valueLimit) {
    let limitDefined = valueLimit > 0 ? valueLimit : undefined;
    if (!limitDefined || numCharacters < limitDefined) {
        return { isExceed: false, value: limitDefined };
    } else {
        return { isExceed: true, value: limitDefined };
    }
}

