const textArea = document.querySelector(".form__text");
const checkboxExcludeSpaces = document.querySelector("#exclude-spaces");
const checkboxLimitCaracters = document.querySelector("#limit-caracters");
const inputLimitCharacters = document.querySelector(".form__input");
const spanCardsValue = document.querySelectorAll(".card__value");
const spanNoSpace = document.querySelector(".card__title-no-space");
const diVWarningLimit = document.querySelector(".form__warning-limit-characters");
const spanWarningLimitValue = diVWarningLimit.querySelector(".form__warning-limit-value");
const spanReadingTime = document.querySelector(".form__reading-time-result");

const PATTERN_LIMIT_INPUT = /[^0-9]/g; // generated by IA

// Update values from UI
function updateCharactersStats(text) {
    const isCheckedExcludeSpaces = checkActivatedExcludeSpace();
    let characters = 0;
    let words = 0;
    let sentences = 0;
    let readingTime = 0;
    let isExcludeSpaces = false;
    let limitCharacters = { isExceed: false, value: undefined };
    if (isCheckedExcludeSpaces) {
        characters = countCharacters(text, "noSpaces");
        isExcludeSpaces = true;
    } else {
        characters = countCharacters(text, "original");
        limitCharacters = checkLimitCharacters(characters);
    }
    words = countWordsSenteces(text, "original").totalWords;
    sentences = countWordsSenteces(text, "original").totalSentences;
    readingTime = calcReadingTime(words);
    updateUI({ characters, words, sentences, readingTime, isExcludeSpaces, limitCharacters });
}

// check if checkbox exclude spaces is checked
function checkActivatedExcludeSpace() {
    let isChecked = checkboxExcludeSpaces.checked;
    return isChecked;
}

// Sanitize input when the user types letter and symbols
inputLimitCharacters.addEventListener("input", () => {
    inputLimitCharacters.value = inputLimitCharacters.value.replace(PATTERN_LIMIT_INPUT, "");
});


// input of the caracteres from text area
function captureTextRealTime() { 
    const text = textArea.value.trim();
    updateCharactersStats(text);
}

// check the limit of characters 
export function checkLimitCharacters(numCharacters) {
    const valueLimit = Number(inputLimitCharacters.value);
    let limitDefined = valueLimit > 0 ? valueLimit : undefined;
    if (numCharacters >= limitDefined) {
        return { isExceed: true, value: limitDefined };
    } else {
        return { isExceed: false, value: limitDefined };
    }
}

// show the input to define limit of characters
function showInputLimitCharacters() {
    let isChecked = this.checked;
    if (isChecked) {
        inputLimitCharacters.setAttribute("aria-hidden", "false");
        inputLimitCharacters.focus();
    } else {
        inputLimitCharacters.setAttribute("aria-hidden", "true");
        inputLimitCharacters.value = "";
        captureTextRealTime();
    }
    inputLimitCharacters.classList.toggle("form__input--active", isChecked);
}

// update UI
function updateUI(states) {
    const readingTime = states["readingTime"];

    // show label No Space
    if (states["isExcludeSpaces"]) {
        spanNoSpace.setAttribute("aria-hidden", "false");
    } else {
        spanNoSpace.setAttribute("aria-hidden", "true");
    }
    spanNoSpace.classList.toggle("card__title-no-space--active", states["isExcludeSpaces"]);


    // show result in the cards
    spanCardsValue.forEach(card => {
        if (Object.hasOwn(states, card.id)) {
            card.textContent = states[card.id] > 0 ? states[card.id].toString().padStart(2, "0") : "00";
        }
    })

    // show the time to reading
    if (readingTime === 0) {
        spanReadingTime.textContent = "0 minute";
    } else if (readingTime > 0 && readingTime < 1) {
        spanReadingTime.textContent = "< 1 minute";
    } else {
        spanReadingTime.textContent = `${Math.ceil(readingTime)} minutes`;
    }

    // show mensagem exceeds limit defined
    if (states["limitCharacters"].isExceed) {
        spanWarningLimitValue.textContent = states["limitCharacters"].value;
        diVWarningLimit.setAttribute("aria-hidden", false);
    } else {
        diVWarningLimit.setAttribute("aria-hidden", true);
    }
    textArea.classList.toggle("form__text--error", states["limitCharacters"].isExceed);
    diVWarningLimit.classList.toggle("form__warning-limit-characters--active", states["limitCharacters"].isExceed);
}

checkboxLimitCaracters.addEventListener("change", showInputLimitCharacters);
checkboxExcludeSpaces.addEventListener("change", captureTextRealTime);
inputLimitCharacters.addEventListener("blur", captureTextRealTime);
textArea.addEventListener("input", captureTextRealTime);

import {
    countCharacters,
    countWordsSenteces,
    calcReadingTime,
} from "./stats-logic.js";