const PATTERN_ONLY_LETTERS = /[a-z]/g; // generated by IA

export function handleDensity(text) {
    const lettersLowerCase = text.toLowerCase(text);
    const letters = lettersLowerCase.match(PATTERN_ONLY_LETTERS);
    if (!letters) return;

    const totalLetters = letters.length;
    // const numberOfLetters = sortByNumberOfLetters(countLetters(letters));
    const numberOfLetters = countLetters(letters);
    console.log(numberOfLetters);
}

function countLetters(letters) {

    const numberOfLetters = letters.reduce((acc, letter) => {
        if (!acc[letter]) {
            acc[letter] = 1;
        } else {
            acc[letter]++;
        }
        return acc;
    }, {});

    return numberOfLetters;
}

function sortByNumberOfLetters(resultNumberOfLetters){
    

}




