const PATTERN_ONLY_LETTERS = /[a-z]/g; // generated by IA

// handle 
export function handleDensity(characters) {
    const letters = getOnlyLetter(characters);
    if (letters) {
        const totalLettersInText = letters.length;
        const resultCountLetters = countLetters(letters);
        const resultStatus = calculeDensity(resultCountLetters, totalLettersInText);
        return resultStatus;
    };

    return [];
}

// capture only text
function getOnlyLetter(characters){
    const lettersLowerCase = characters.toLowerCase(characters);
    return lettersLowerCase.match(PATTERN_ONLY_LETTERS);
}

// counter the letters and return a map with letter and number
function countLetters(letters) {

    const numberOfLetters = letters.reduce((acc, letter) => {
        if (!acc[letter]) {
            acc[letter] = 1;
        } else {
            acc[letter]++;
        }
        return acc;
    }, {});

    return numberOfLetters;
}

// calculate the density
function calculeDensity(resultCountLetters, totalLettersInText) {
    const ResultComposition = [];
    for (const key in resultCountLetters) {
        const count = resultCountLetters[key];
        const percentage = (count / totalLettersInText) * 100;
        ResultComposition.push({ letter: key, count: count, percentage: percentage.toFixed(2) });
    }
    return ResultComposition;
}

// sort descending order of result
export function sortByNumberOfLetters(density) {
    const copyResultNumberOfLetters = [...density];
    const sorted = copyResultNumberOfLetters.sort((a, b) => {
        return b.count - a.count;
    });
    return sorted;
}


