const PATTERN_ONLY_LETTERS = /[a-z]/g; // generated by IA

export function handleDensity(text) {
    const textLowerCase = text.toLowerCase(text);
    const letters = textLowerCase.match(PATTERN_ONLY_LETTERS);
    if (!letters) return;

    const totalLettersInText = letters.length;
    // const numberOfLetters = sortByNumberOfLetters(countLetters(letters));
    const numberOfLetters = countLetters(letters);
    calculeDensity(numberOfLetters, totalLettersInText);
}

function countLetters(letters) {

    const numberOfLetters = letters.reduce((acc, letter) => {
        if (!acc[letter]) {
            acc[letter] = 1;
        } else {
            acc[letter]++;
        }
        return acc;
    }, {});

    return numberOfLetters;
}

function calculeDensity(numberOfLetters, totalLettersInText){
    const densityResult = [];
    for (const key in numberOfLetters) {
        const count = numberOfLetters[key];
        const percentage = (count / totalLettersInText) * 100;
        densityResult.push({letter: key, count: count, percentage: percentage});
    }
    console.log(densityResult);
    return densityResult;
}






function sortByNumberOfLetters(resultNumberOfLetters){
    

}




