const PATTERN_LIMIT_INPUT = /[^0-9]/g; // generated by IA

// Sanitize input when the user types letter and symbols
export function sanitizeLimitInput(value) {
    return value.replace(PATTERN_LIMIT_INPUT, "");
}

// check the limit of characters 
export function checkLimitCharacters(numCharacters, valueLimit) {
    let limitDefined = valueLimit > 0 ? valueLimit : undefined;
    if (!limitDefined || numCharacters < limitDefined) {
        return { isExceed: false, value: limitDefined };
    } else {
        return { isExceed: true, value: limitDefined };
    }
}


// Sanitize input when the user types letter and symbols
function handleLimitInput(){
    const sanitizeValue = sanitizeLimitInput(inputLimitCharacters.value);
    inputLimitCharacters.value = sanitizeValue;
}

// Get the value of the input limit
function handleStatesInputLimit() {
    updateCharactersStats();
}

// show mensagem exceeds limit defined
    if (states["limitCharacters"].isExceed) {
        spanWarningLimitValue.textContent = states["limitCharacters"].value;
        diVWarningLimit.setAttribute("aria-hidden", "false");
        textArea.setAttribute("disabled", "disabled");
    } else {
        diVWarningLimit.setAttribute("aria-hidden", "true");
        textArea.removeAttribute("disabled");
    }
    textArea.classList.toggle("form__text--error", states["limitCharacters"].isExceed);
    diVWarningLimit.classList.toggle("form__warning-limit-characters--active", states["limitCharacters"].isExceed);